apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: easyshop-hack
type: opaque
stringData:
  NEXTAUTH_SECRET: V7a3IJzMM75LnVsKcUByhi6ET8x0apBLvU1IEZ5YOI8=
  JWT_SECRET: 3b7586942e49a313d8410ac4908d071f30ff0c5ce8fff1f90f5c1c8c8b807107